import keyMirror from 'key-mirror'

export default keyMirror({
  CATEGORY_PICK: null,
  UPDATE_SKILLS_LIST: null,
  UPDATE_SKILL_ITEM: null,
  UPDATE_ARTICLE: null,
  UPDATE_WORK: null,
  UPDATE_ABOUT: null,
  DELETE_SKILLS_LIST: null,
  DELETE_SKILL_ITEM: null,
  DELETE_ARTICLE: null,
  DELETE_ARTICLE_CATEGORY: null,
  DELETE_WORK_CATEGORY: null,
  DELETE_WORK: null,
  POST_SKILLS_LIST: null,
  POST_SKILL_ITEM: null,
  POST_ARTICLE: null,
  POST_ARTICLE_CATEGORY: null,
  POST_CATEGORY: null,
  POST_WORK: null,
  LOAD_POPULATED_SKILLS: null,
  LOAD_SKILL: null,
  LOAD_SKILLS_LIST: null,
  LOAD_SKILL_ITEM: null,
  LOAD_ABOUT: null,
  LOAD_ARTICLE: null,
  LOAD_ARTICLE_BY_CATEGORY: null,
  LOAD_ARTICLE_PAGE: null,
  LOAD_ALL_ARTICLES: null,
  LOAD_ARTICLE_CATEGORIES: null,
  LOAD_CATEGORIES: null,
  LOAD_WORK: null,
  LOAD_ALL_WORKS: null,
  START: null,
  SUCCESS: null,
  FAIL: null
})